import './index.scss'
import LogoS from '../../../assets/images/logo-s.png'
import { useRef } from 'react'

const Logo = () => {
  const bgRef = useRef()
  const outlineLogoRef = useRef()
  const solidLogoRef = useRef()

  return (
    <div className="logo-container">
      <img className="solid-logo" src={LogoS} alt="S" />
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        width="1000"
        zoomAndPan="magnify"
        viewBox="0 0 750 599.999999"
        height="800"
        preserveAspectRatio="xMidYMid meet"
        version="1.0"
        style={{ zoom: '0.5' }}
        visibility="visible"
      >
        <g className="svg-container">
          <line
            stroke="#000000"
            y1="30px"
            id="line1"
            x1="85.5px"
            strokeWidth="3px"
            d=""
            y2="580.5px"
            x2="282px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="577.5px"
            id="line2"
            x1="282px"
            strokeWidth="3px"
            y2="576px"
            x2="484.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="574.5px"
            id="line3"
            x1="484.5px"
            strokeWidth="3px"
            d=""
            y2="30px"
            x2="676.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="43.5px"
            id="line4"
            x1="751.5px"
            strokeWidth="3px"
            y2="43.5px"
            x2="751.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="177px"
            id="line5"
            x1="459px"
            strokeWidth="3px"
            y2="177px"
            x2="459px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="31.5px"
            id="line6"
            x1="85.5px"
            strokeWidth="3px"
            y2="580.5px"
            x2="282px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="577.5px"
            id="line7"
            x1="283.5px"
            strokeWidth="3px"
            y2="577.5px"
            x2="483px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="573px"
            id="line8"
            x1="481.5px"
            strokeWidth="3px"
            y2="30px"
            x2="676.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="33px"
            id="line9"
            x1="678px"
            strokeWidth="3px"
            y2="30px"
            x2="496.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="33px"
            id="line10"
            x1="498px"
            strokeWidth="3px"
            y2="394.5px"
            x2="385.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="394.5px"
            id="line11"
            x1="387px"
            strokeWidth="3px"
            y2="28.5px"
            x2="273px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="28.5px"
            id="line12"
            x1="274.5px"
            strokeWidth="3px"
            y2="31.5px"
            x2="85.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="49.5px"
            id="line13"
            x1="123px"
            strokeWidth="3px"
            y2="594px"
            x2="316.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="594px"
            id="line14"
            x1="316.5px"
            strokeWidth="3px"
            y2="594px"
            x2="520.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="595.5px"
            id="line15"
            x1="522px"
            strokeWidth="3px"
            y2="51px"
            x2="711px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="49.5px"
            id="line16"
            x1="709.5px"
            strokeWidth="3px"
            y2="51px"
            x2="532.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="52.5px"
            id="line17"
            x1="535.5px"
            strokeWidth="3px"
            y2="415.5px"
            x2="421.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="415.5px"
            id="line18"
            x1="423px"
            strokeWidth="3px"
            y2="51px"
            x2="307.5px"
            transform=""
          ></line>
          <line
            stroke="#000000"
            y1="51px"
            id="line19"
            x1="310.5px"
            strokeWidth="3px"
            y2="51px"
            x2="124.5px"
            transform=""
          ></line>
        </g>
      </svg>
    </div>
  )
}

export default Logo
